[project]
name = "jup_ag_sdk"
version = "0.0.1"
authors = [
  { name="Fiji", email="charismoutafidis@gmail.com" },
]
description = "Python SDK for Jupiter Exchange APIs."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/cmoutafidis/jup-ag-sdk"
Issues = "https://github.com/cmoutafidis/jup-ag-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
